language: erlang

before_script:
  - "./configure --libdir=/usr/lib/i386-linux-gnu --crtprefix=/usr/lib/i386-linux-gnu --sysincludepaths=/usr/local/include:/usr/include/i386-linux-gnu:/usr/include:{B}/include --libpaths=/usr/lib/i386-linux-gnu:/usr/lib:/lib/i386-linux-gnu:/lib:/usr/local/lib"

script:
  - "make test"
